---
- name: Provision Vagrant vm
  hosts: all
  gather_facts: no
  become: yes

  vars:
    default_packages:
      - curl
      - jq
      - vim
      - wget

  tasks:
    - name: Install default packages
      apt:
        name: "{{default_packages}}"
        state: present
